### ISSUE TITLE
CMake fails to use Autools built zfp and hdf5

### ISSUE THREAD

**Issue by brtnfld** [LLNL/H5Z-ZFP#57]
When pointing to autotools build hdf5 and zfp, 

-D CMAKE_PREFIX_PATH="$HDF5" \
-D ZFP_DIR="$ZFP" \

h5z-zfp says it finds HDF5  but does not include the correct links in the compilation.
zfp needs to have *.cmake files, so Autotools builds are not supported for zfp.

**Comment by jwsblokland** [comment]
Hello @brtnfld I have fixed the problem with the autotools build HDF5 (see pull request https://github.com/LLNL/H5Z-ZFP/pull/59). I noticed that one for the Fortran tests fails but I have no clue why since I have not change any of the source files.

Regarding ZFP and the autotools. That is a bit of a tricky problem. The zfp library can be build with OpenMP support and with the ZFP cmake config files you can nicely propagate this OpenMP dependency to the H5Z_ZFP and even to the final application via the H5Z_ZFP cmake config files. This means the CMake project of the final application does not have to change anything to pick up this OpenMP dependency. With the autotool build of ZFP it is much more difficult to determine this dependency and to propagate to a final application. The alternative is that such application should add OpenMP flag if ZFP depends on OpenMP. This should be done even in the case if the application itself does not make directly use of OpenMP.

**Comment by markcmiller86** [comment]
@jwsblokland just curious but what happens regarding the OpenMP dependency when H5Z-ZFP is used as a bonified dynamic plugin (e.g. HDF5 library loads it via `dlopen()` @ runtime instead of via link-time of the application)? 

Should an OpenMP-enabled ZFP library install be able to support *both* non-OpenMP dependent applications that want to use it as well as OpenMP dependent applications (which in turn may or may not want to infact utilize ZFP's OpenMP features?)? Or, are two separate installs required for that? In my experience with something similar (MPI dependencies in HDF5 library), I've only ever seen it handled by having two separate installs; one with the MPI dependence and one without.

**Comment by jwsblokland** [comment]
@markcmiller86 That is a interesting question. If I build H5Z-ZFP using gcc in combination with OpenMP-enabled static ZFP library, I see that the plugin depends on the shared library `libgomp.so.1`. At least that is what the program `ldd` tells me. So it looks like you have to create two separate installs if you want a plugin with and without OpenMP.

**Comment by markcmiller86** [comment]
Resolved by #59
