### ISSUE TITLE
8-bit stream word size limitation

### ISSUE THREAD

**Issue by jwsblokland** [LLNL/H5Z-ZFP#69]
Hello Mark,

Not really an issue, but more a question. A colleague of mine discovered that the H5Z_ZFP filter requires that the ZFP library needs to build with the CMake option:
   `-DZFP_BIT_STREAM_WORD_SIZE=8`

This are the lines in the code which checks on the stream_word_bits:
https://github.com/LLNL/H5Z-ZFP/blob/7b34cacf8e599aeb2fa8f3096281d620c4eab486/src/H5Zzfp.c#L147-L149

Now, I am wondering what is reason for this 8-bit limitation?

Best regards,
   Jan-Willem

**Comment by markcmiller86** [comment]
I believe the reason is that we need to *guarantee* machine portable data for HDF5 files and the only way to do that is to use 8-bit word size.

If I recall, I think it has a ~10% effect on time-performance of ZFP library and none on space-performance.

**Comment by markcmiller86** [comment]
FYI, regardless of the reason...my clear recollection is that we force 8-bit mode here as per instructions from the boss, @lindstro. So, maybe Peter has a better explanation.

**Comment by lindstro** [comment]
Mark is right--the reason is that a larger word size would require dealing with machine-specific endianness issues to ensure portability.  It may be possible to have HDF5 handle any necessary byte swapping (Mark?), but one problem with this is that a zfp stream currently must be a whole number of words.  Hence, a stream written with 8-bit word size might not be readable using, say, a 64-bit word size as that might require reading past the end of the stream, and detecting such a condition in the innermost loop would be expensive.

In retrospect, I made some dumb design decisions that hopefully can be addressed in the next major version of zfp.  I'm open to any suggestions as to how to best handle this, ideally without adverse performance implications.

**Comment by jwsblokland** [comment]
@lindstro and @markcmiller86, thanks for this detailed answer. It explains a lot and now I understand why there is this 8-bit limitation.
