### ISSUE TITLE
Use with python

### ISSUE THREAD

**Issue by greaber** [LLNL/H5Z-ZFP#70]
Sorry to ask a really basic question here, but I was wondering if it is possible to use this library with python (presumably using`h5py`) or if the only way to use ZFP in python is with https://pypi.org/project/pyzfp/

**Comment by markcmiller86** [comment]
@greaber hmm....based on your question, it isn't entirely clear to me what you may be looking for.

I've never heard of pyzfp but looking at the project, it appears to use ZFP to compress numpy arrays in python memory. H5Z-ZFP on the other hand uses ZFP to compress data as it is being written (or decompress as it is being read) to an HDF5 file.

This is because ZFP supports multiple interfaces for different purposes. One is its [compressed streaming interface](https://zfp.readthedocs.io/en/release0.5.5/high-level-api.html) and that is what H5Z-ZFP uses. Another is its [compressed arrays (in C++ or C)](https://zfp.readthedocs.io/en/release0.5.5/arrays.html) designed to enable software developers to write code that operates on in-memory compressed arrays in a natural way hiding many of the details of compressing and decompressing.

Which are you looking for? Or, are you looking for both?

**Comment by greaber** [comment]
Hi, @markcmiller86.  I store numpy arrays in H5 files and would like them to be compressed on disk.  I don't care about compressing data in memory.  So H5Z-ZFP sounds like a good fit, but it wasn't clear to me if I could use it directly in python.  If not, a library like pyzfp (or any other python-based interface there might be to ZFP) could be a reasonable alternative since presumably I could manually compress/decompress data before writing/after reading.

**Comment by markcmiller86** [comment]
Ok, then, yes I think H5Z-ZFP would work for you. I think you should have a look at [h5py](https://www.h5py.org/) and see if it is possible to use plugin-style filters with it and then, if so, you should be good to go I think. Would be interested to know what you learn.

**Comment by vasole** [comment]
@greaber 

To make your life easy and/or for a quick test, you can give a try to the hdf5plugin module. It provides common filters (including zfp) for their use with h5py https://github.com/silx-kit/hdf5plugin

**Comment by greaber** [comment]
@vasole, thank. I noticed that recently.  Does it have a disadvantage over this repo (like lower speed)?

**Comment by vasole** [comment]
If you use the supplied wheel, you might get a version not optimized for your hardware. However, it should be straightforward to compile it on your system.

The main advantage of using hdf5plugin is that we took provisions to prevent linking against a specific version of the HDF5 library. Most HDF5 plugins put a dependency on the version of the library used to build them. If you do not need that and you want always the latest version you should be better served by this repository. Therefore my `To make your life easy and/or for a quick test`

**Comment by greaber** [comment]
Thanks!

**Comment by markcmiller86** [comment]
@greaber one quick thing to be aware of...using HDF5 filters as plugins *requires* the use of the *generic* HDF5 interface to filters...an arbitrary array of *unsigned integer* parameters. You won't be able to use a properties-like interface. See remarks regard [interfaces](https://h5z-zfp.readthedocs.io/en/latest/interfaces.html) in the docs.

ZFP's *native* interface requires some *double precision* parameters. These can get passed to the plugin via generic interface using type-punning but not necessarily in a machine portable way. So, you may not be able to _easily_ write machine-portable python code where H5Z-ZFP parameter passing is concerned.

**Comment by lindstro** [comment]
@greaber In case you want to use zfp to compress NumPy arrays without HDF5, I would suggest the official repo maintained by the zfp team: https://pypi.org/project/zfpy/.  Look out for a new release in the coming weeks.

**Comment by lindstro** [comment]
@markcmiller86 I've probably asked this before, but would it be reasonable to change the `cd_values` interface to H5Z-ZFP to use the same integer parameters that zfp records in `zfp_stream`?  Currently, the filter accepts `cd_values` as an `unsigned int` array, uses unsafe type punning to convert those to, say, a double-precision tolerance, feeds that parameter to zfp, which (safely, without type punning) converts it to a set of four integers (three unsigned and one signed) that differ entirely from the `cd_values` parameters.  Or do the `cd_values` themselves get embedded in the HDF5 file, in which case such a change would not be backwards compatible?

**Comment by markcmiller86** [comment]
> @markcmiller86 I've probably asked this before, but would it be reasonable to change the `cd_values` interface to H5Z-ZFP to use the same integer parameters that zfp records in `zfp_stream`?

I honestly can't recall if you have asked this but I did wind up asking myself as I was writing the above note to @greaber.

But, the short answer is no, not if we are going to offer the application (caller) the ability to specify a `double rate` and then use the filter as an HDF5 *plugin*. In that case, the application (caller) never links with the zfp library (or any other library) that could convert its *double* parameters to ZFP's integer metadata. I mean the code to do that conversion needs to be somewhere. Even if it was available in the plugin, how does the caller access it via HDF5's generic interface?

If we don't restrict ourselves to using the filter as a *plugin* (and the subsequent generic HDF5 interface for that), then we can rely on the application linking to some additional library to support a better interface. And, that is when H5Z-ZFP is used as a *library* instead of a dynamically loaded plugin.

Another option...provide a header-only interface to the functions that take ZFP's double params. Applications can include that interface and use it to pass ZFP integer parameters to the filter. That might be a better route. But, even that is, in practice, more involved than what would ordinarily be required for an HDF5 *plugin*.

**Comment by lindstro** [comment]
I think I'm missing something.  Currently, the user needs to call _some_ function--regardless of where that function lives--that converts a `double` to a set of `cd_values`.  We're not asking the user to do this by hand, right?  Instead of type punning, could that function not convert to zfp's internal integer parameters?  I'm afraid that I don't know enough about "HDF5's generic interface" to understand what the issues are.

**Comment by markcmiller86** [comment]
> We're not asking the user to do this by hand, right?

In the [generic interface](https://h5z-zfp.readthedocs.io/en/latest/interfaces.html#generic-interface), yes, we kinda are.

I provide some CPP macros to facilitate that but its really up to the caller to then `#include <H5Zzfp_plugin.h>` to get access to those macros and its non-essential as long as they obey the data layout indicated in the table in the docs there.

**Comment by lindstro** [comment]
Could those macros be replaced with inline functions that essentially replicate what the `zfp_stream_set_XXX()` [family of functions](https://zfp.readthedocs.io/en/release0.5.5/high-level-api.html#compression-parameters) do?

**Comment by markcmiller86** [comment]
> Could those macros be replaced with inline functions that essentially replicate what the `zfp_stream_set_XXX()` [family of functions](https://zfp.readthedocs.io/en/release0.5.5/high-level-api.html#compression-parameters) do?

Yes and no.

Yes, anything is possible.

No, if we want to offer applications who do *nothing more* than point to a dynamic library implementing the H5Z-ZFP filter to ability to actually use the filter as an HDF5 plugin.

**Comment by lindstro** [comment]
I'm afraid I still don't understand what the fundamental issues are.  An application that wants to use the filter/plugin for compression must necessarily specify zfp's compression parameters.  They must call _some_ function to supply the filter/plugin with those parameters.  If that function does not accept anything but `cd_values`, then why can we not provide a separate function or even a macro in a header file that translates human readable parameters to `cd_values` that correspond to zfp's `minrate`, `maxrate`, `maxprec`, and `minexp`, i.e., without type punning?  I mean, isn't that what the "generic interface" does?  If instead the filter/plugin API includes a function that accepts human readable parameters, then we can do whatever we want in that function to convert the parameters to the metadata needed by zfp (via H5Z-ZFP).

By the way, in this context, what is the difference between "H5Z-ZFP filter" and "HDF5 plugin"?

**Comment by markcmiller86** [comment]
> then why can we not provide a separate function or even a macro in a header file that translates human readable parameters to `cd_values` that correspond to zfp's `minrate`, `maxrate`, `maxprec`, and `minexp`, i.e., without type punning?

We can. That is what the **Another option** remark in [this comment](https://github.com/LLNL/H5Z-ZFP/issues/70#issuecomment-963443779) was getting at.

**Comment by lindstro** [comment]
Gotcha.  I guess I got hung up on "But, the short answer is no." :-)

Out of curiosity, how do zfp's compression parameters get encoded in the HDF5 file?

**Comment by markcmiller86** [comment]
> Out of curiosity, how do zfp's compression parameters get encoded in the HDF5 file?

As the stream's meta header

**Comment by lindstro** [comment]
OK, so via `zfp_write_header()`.  This means that at some point the compression settings have been converted to [zfp expert mode parameters](https://zfp.readthedocs.io/en/release0.5.5/modes.html#expert-mode) `{minbits, maxbits, maxprec, minexp}`.

I think it would be worthwhile to modify the generic interface to accept expert mode parameters stored as four `cd_values`.  Those are fairly easy to set manually, via the zfp library, or through a new set of macros or inline functions.  We wouldn't have to worry about undefined behavior associated with type punning or the significant difficulties of manually encoding doubles as `cd_values`, e.g., on the `h5repack` command line.

**Comment by markcmiller86** [comment]
> OK, so via `zfp_write_header()`?

Yes...

https://github.com/LLNL/H5Z-ZFP/blob/7b34cacf8e599aeb2fa8f3096281d620c4eab486/src/H5Zzfp.c#L387-L389

> I think it would be worthwhile to modify the generic interface to accept expert mode parameters stored as four `cd_values`.

The *generic* interface already supports that with `cd_values[0]==4` and remaining `cd_values[]` entries the ZFP *expert* parameters. That said, no human I know (other than maybe you) knows how to set those given a goal `rate` of 2.5 bits or an `accuracy` of 0.001. So, humans want an interface that allows them to specify `rate` or `accuracy`. 

The only code I know that reliably converts a `double rate` or  `double accuracy` to ZFP meta integers is in the ZFP library. So, any caller that wants that will *have to link to it* to get that. Thats the kicker here, @lindstro. Do you have maybe a CPP only version of that code? That would help. It would mean callers could just `#include` it to get some help much like they might already decide to `#include <H5Zzfp_plugin.h>` to get the *current* macros that do the type-punning.

If the app is already willing to link to a new lib to use H5Z-ZFP, then it should have no trouble linking to the teeny/tiny property *lib* that comes with H5Z-ZFP allow it to control the filter via a more natural, HDF5 properties interface. In that case, I claim they should just then be using the filter as a *library* instead of a dynamic plugin and they will link to `libh5zzfp.a` and get everything the need.

When the application wishes to use the filter as it would any other HDF5 plugin, then they are not willing to link to any new library. This is especially true of a utility like `h5repack` though that is obviously a special case too.

I don't want to force apps to link to a lib they may not either know how to or want to, etc.  That is why the *properties* interface is optional but nonetheless highly recommended.

The one take-away I've learned from this is to maybe offer another option for the *generic* interface and that is to permit callers to pass the same bytes as `zfp_write_header()` would produce, through the generic interface. We can't do that and it could be useful though how they'd obtain the method(s) to produce those bytes is up to them...(either link to zfp, h5zzfp or maybe there's a convenience header file)

**Comment by markcmiller86** [comment]
BTW...I should also point out that making HDF5's generic interface `cd_values` take on ZFP's meta integers basically would imply that that part of ZFP (e.g. how header bytes are laid out and interpreted)  is then part of its *public* interface. I assume that is already true but wanted to check and confirm.

**Comment by lindstro** [comment]
> The _generic_ interface already supports that with `cd_values[0]==4` and remaining `cd_values[]` entries the ZFP _expert_ parameters. That said, no human I know (other than maybe you) knows how to set those given a goal `rate` of 2.5 bits or an `accuracy` of 0.001. So, humans want an interface that allows them to specify `rate` or `accuracy`.

I agree that it would be a big ask to require humans to memorize how to set those, even though this info is [documented](https://zfp.readthedocs.io/en/release0.5.5/modes.html#fixed-rate-mode) and not unreasonably complicated:

**fixed rate in _d_ dimensions**
```
minbits = maxbits = (1 << (2 * d)) * rate
maxprec = ZFP_MAX_PREC
minexp = ZFP_MIN_EXP
```

**fixed precision**
```
minbits = ZFP_MIN_BITS
maxbits = ZFP_MAX_BITS
maxprec = precision
minexp = ZFP_MIN_EXP
```

**fixed accuracy**
```
minbits = ZFP_MIN_BITS
maxbits = ZFP_MAX_BITS
maxprec = ZFP_MAX_PREC
minexp = floor(log2(tolerance))
```

Of course we'd want to provide helper functions as well.  But surely you agree that no human could translate a tolerance of 0.001 by converting its IEEE double-precision binary representation to two 32-bit integers (in the correct endian order), as would be required now, whereas they'd at least have a chance to do so via expert mode parameters (e.g., floor(log2(0.001)) = -10).  Setting fixed rate or precision is even easier.

> The only code I know that reliably converts a `double rate` or `double accuracy` to ZFP meta integers is in the ZFP library. So, any caller that wants that will _have to link to it_ to get that. Thats the kicker here, @lindstro. Do you have maybe a CPP only version of that code?

Sure, it's just a [few lines of code](https://github.com/LLNL/zfp/blob/6aec9dc420bc692873c9b3e270d7c23e4f61d2fa/src/zfp.c#L736) that could be implemented as macros.  If we're willing to make some reasonable assumptions, e.g., that the user doesn't need word alignment and ridiculously low rates, then the code for setting fixed rate is even simpler (see above).

> That would help. It would mean callers could just `#include` it to get some help much like they might already decide to `#include <H5Zzfp_plugin.h>` to get the _current_ macros that do the type-punning.

Agreed.

> I don't want to force apps to link to a lib they may not either know how to or want to, etc. That is why the _properties_ interface is optional but nonetheless highly recommended.

Makes sense.

**Comment by markcmiller86** [comment]
> But surely you agree that no human could translate a tolerance of 0.001 by converting its IEEE double-precision binary representation to two 32-bit integers (in the correct endian order), as would be required now

I don't mean to be argumentative but that is wholly incorrect. They would `#include <H5Zzfp_plugin.h>` which provides [simply macros](https://h5z-zfp.readthedocs.io/en/latest/interfaces.html#generic-interface) and which H5Z-ZFP test codes do. What you propose above is a different set of macros but with the added benefit that no type punning is involved. Good idea and is what I meant by...

> 
> Another option...provide a header-only interface to the functions that take ZFP's double params. Applications can include that interface and use it to pass ZFP integer parameters to the filter. That might be a better route. But, even that is, in practice, more involved than what would ordinarily be required for an HDF5 _plugin_.

**Comment by lindstro** [comment]
> BTW...I should also point out that making HDF5's generic interface `cd_values` take on ZFP's meta integers basically would imply that that part of ZFP (e.g. how header bytes are laid out and interpreted) is then part of its _public_ interface. I assume that is already true but wanted to check and confirm.

The zfp header encoding is actually different from the four integer parameters and requires yet another layer of translation.  In fact, the four integers can usually be encoded in only 12 bits total; at most, 64 bits are needed.  The common denominator is the expert mode four-parameter representation, and it's of course part of the public interface through [`zfp_stream_set_params()`](https://zfp.readthedocs.io/en/release0.5.5/high-level-api.html#c.zfp_stream_set_params).  The zfp header also contains information about the dimensions and scalar type of the array being compressed.

The binary representation of the header and zfp code stream is currently not exposed to the outside world.  You'll have to use zfp as a black box to read and write zfp streams.  Maybe one day I'll find time to fully document the meaning of each individual bit in the zfp binary representation.

**Comment by lindstro** [comment]
> > But surely you agree that no human could translate a tolerance of 0.001 by converting its IEEE double-precision binary representation to two 32-bit integers (in the correct endian order), as would be required now
> 
> I don't mean to be argumentative but that is wholly incorrect. They would `#include <H5Zzfp_plugin.h>` which provides [simply macros](https://h5z-zfp.readthedocs.io/en/latest/interfaces.html#generic-interface) and which H5Z-ZFP test codes do. What you propose above is a different set of macros but with the added benefit that no type punning is involved.

Right.  What I meant is that the user would, for example, have a chance of supplying expert-mode parameters to `h5repack` without having to run a separate utility like `print_h5repack_farg` that converts a double-precision rate to a collection of integers.  They could actually do the math in their head, consult a calculator, or write a couple of lines of code.  This is more complicated with type punning, which could or even _should_ fail if not implemented carefully--I've run across compilers that actually caused undefined behavior with type punning and gave the "wrong" answer.
