### ISSUE TITLE
Got HDF5 error when H5Z-ZFP plugin used with HDF5 1.12.1, NetCDF 4.8.1 and zfp unbiased branch

### ISSUE THREAD

**Issue by halehawk** [LLNL/H5Z-ZFP#75]
I recently used "make" building H5Z-ZFP plugin with HDF_HOME is HDF5 1.12.1 and ZFP_HOME is zfp unbiased branch, then I used this plugin with NetCDF 4.8.1 which was built on HDF5 1.12.1. I kept getting HDF5 error at nc_enddef. I have no such problem with  HDF5 prebuilt plugin provided at https://portal.hdfgroup.org/display/support/HDF5%201.12.1 on the same HDF5, NetCDF versions. Could you please help me to solve it?

**Comment by halehawk** [comment]
Here is my ldd results
[ldd_nccopy.txt](https://github.com/LLNL/H5Z-ZFP/files/7991607/ldd_nccopy.txt)

**Comment by markcmiller86** [comment]
I am confused by what you mean by `zfp unbiased branch`? Maybe you mean the *default* branch...which is the branch name [`develop`](https://github.com/LLNL/zfp)?

When you did the `make` of H5Z-ZFP, did you also do a `make check` to confirm it passes all its tests? If not, can you please do that? Use the exact same `make` command you used to build/install it but instead of a make target of `install` or `all` specify a make target of `check`.

I suspect it will fail. You need to use a *released* version of the ZFP library, not a version currently under development. So, go to ZFP's [*releases* ](https://github.com/LLNL/zfp/releases) and grab the latest official release there and try that.

**Comment by halehawk** [comment]
Sure, I will try the make check.
We really like this develop branch which can give us better error
distribution compared to the formal release one.

**Comment by markcmiller86** [comment]
> We really like this develop branch which can give us better error distribution compared to the formal release one.

Are you saying that ZFP compression *performance* or *behavior* on their `develop` branch is better than the `0.5.5` release? If so, we can try to expedite a release of H5Z-ZFP to accomodate it but I'd rather have a stable API to work with.

@lindstro can you comment at all?

**Comment by lindstro** [comment]
@halehawk is referring to the `feature/unbiased-error` branch, though that branch has already been merged into `develop`.  This feature cancels bias in compression errors using proper rounding (when enabled using a compile-time macro) and generally improves accuracy per stored bit over zfp 0.5.5.  This feature will become available in the next version of zfp, which we hope to release in the coming weeks.

Note that when this new rounding mode, `ZFP_ROUND_FIRST`, is enabled, compressed files will in general differ.  However, older zfp versions (0.5.x) are able to correctly decompress files compressing with rounding on.  However, the zfp checksum tests have not been updated to account for differences in the compressed stream.  I don't know if rounding also breaks any H5Z-ZFP tests.

There's also a new `ZFP_ROUND_LAST` mode that does not impact compressed files but which changes the values during decompression.  It, too, is backwards compatible in the sense that it works with files generated by zfp 0.5.x.

If there are issues with getting H5Z-ZFP to work with the latest zfp `develop`, then we need to resolve those soon so that the filter is compatible with the next release.  I don't know what the issues are, specifically, but am happy to help in whatever way I can.

**Comment by markcmiller86** [comment]
> If there are issues with getting H5Z-ZFP to work with the latest zfp `develop`, then we need to resolve those soon so that the filter is compatible with the next release. I don't know what the issues are, specifically, but am happy to help in whatever way I can.

I can take a look at those issues, if any, next week possibly.

Is `ZFP_ROUND_FIRST` and `ZFP_ROUND_LAST` a compile time or run-time control? IF compile time, we could maybe effect which variant of H5Z-ZFP using different paths to two differently compiled variants of the plugin.

**Comment by lindstro** [comment]
Thanks, Mark.  These macros are currently set at compile time.  I believe we could alternatively store the rounding mode in the `zfp_stream` struct to allow the user to change it at run time; that's something I hadn't considered.

`ZFP_ROUNDING_MODE` is currently an experimental feature, and I'm reluctant to spend more time making API changes and adding new tests to support different rounding modes at run time.  So for now, let's assume that the mode is set at compile time.

**Comment by markcmiller86** [comment]
Which default for rounding mode do you recommend or does ZFP use? first or last?

**Comment by markcmiller86** [comment]
@lindstro also, is there a way for H5Z-ZFP to *interrogate* which rounding mode ZFP is using/built with? Is it merely a matter of...

```
#ifdef ZFP_ROUND_FIRST
#DO SOMETHING
#endif
```

**Comment by halehawk** [comment]
Here is the make check error:
gcc test_write_lib.o -o test_write_lib -Wl,-rpath,/glade/work/haiyingx/CMake-hdf5-1.12.1/HDF_Group/HDF5/1.12.1/lib -Wl,-rpath,/glade/work/haiyingx/zfp_unbiased/install/lib64 -L../src -L/glade/work/haiyingx/CMake-hdf5-1.12.1/HDF_Group/HDF5/1.12.1/lib -L/glade/work/haiyingx/zfp_unbiased/install/lib64 -lh5zzfp -lhdf5 -lzfp -lm 
gcc -c test_read.c -o test_read_lib.o -fPIC -I../src -I/glade/work/haiyingx/zfp_unbiased/install/include -I/glade/work/haiyingx/CMake-hdf5-1.12.1/HDF_Group/HDF5/1.12.1/include
gcc test_read_lib.o -o test_read_lib -Wl,-rpath,/glade/work/haiyingx/CMake-hdf5-1.12.1/HDF_Group/HDF5/1.12.1/lib -Wl,-rpath,/glade/work/haiyingx/zfp_unbiased/install/lib64 -L../src -L/glade/work/haiyingx/CMake-hdf5-1.12.1/HDF_Group/HDF5/1.12.1/lib -L/glade/work/haiyingx/zfp_unbiased/install/lib64 -lh5zzfp -lhdf5 -lzfp 
HDF5-DIAG: Error detected in HDF5 (1.12.1) thread 0:
  #000: /glade/work/haiyingx/CMake-hdf5-1.12.1/hdf5-1.12.1/src/H5D.c line 141 in H5Dcreate2(): unable to create dataset
    major: Dataset
    minor: Unable to create file
  #001: /glade/work/haiyingx/CMake-hdf5-1.12.1/hdf5-1.12.1/src/H5VLcallback.c line 1806 in H5VL_dataset_create(): dataset create failed
    major: Virtual Object Layer
    minor: Unable to create file
  #002: /glade/work/haiyingx/CMake-hdf5-1.12.1/hdf5-1.12.1/src/H5VLcallback.c line 1771 in H5VL__dataset_create(): dataset create failed
    major: Virtual Object Layer
    minor: Unable to create file
  #003: /glade/work/haiyingx/CMake-hdf5-1.12.1/hdf5-1.12.1/src/H5VLnative_dataset.c line 73 in H5VL__native_dataset_create(): unable to create dataset
    major: Dataset
    minor: Unable to initialize object
  #004: /glade/work/haiyingx/CMake-hdf5-1.12.1/hdf5-1.12.1/src/H5Dint.c line 396 in H5D__create_named(): unable to create and link to dataset
    major: Dataset
    minor: Unable to initialize object
  #005: /glade/work/haiyingx/CMake-hdf5-1.12.1/hdf5-1.12.1/src/H5L.c line 1767 in H5L_link_object(): unable to create new link to object
    major: Links
    minor: Unable to initialize object
  #006: /glade/work/haiyingx/CMake-hdf5-1.12.1/hdf5-1.12.1/src/H5L.c line 2009 in H5L__create_real(): can't insert link
    major: Links
    minor: Unable to insert object
  #007: /glade/work/haiyingx/CMake-hdf5-1.12.1/hdf5-1.12.1/src/H5Gtraverse.c line 837 in H5G_traverse(): internal path traversal failed
    major: Symbol table
    minor: Object not found
  #008: /glade/work/haiyingx/CMake-hdf5-1.12.1/hdf5-1.12.1/src/H5Gtraverse.c line 613 in H5G__traverse_real(): traversal operator failed
    major: Symbol table
    minor: Callback failed
  #009: /glade/work/haiyingx/CMake-hdf5-1.12.1/hdf5-1.12.1/src/H5L.c line 1815 in H5L__link_cb(): unable to create object
    major: Links
    minor: Unable to initialize object
  #010: /glade/work/haiyingx/CMake-hdf5-1.12.1/hdf5-1.12.1/src/H5Oint.c line 2468 in H5O_obj_create(): unable to open object
    major: Object header
    minor: Can't open object
  #011: /glade/work/haiyingx/CMake-hdf5-1.12.1/hdf5-1.12.1/src/H5Doh.c line 289 in H5O__dset_create(): unable to create dataset
    major: Dataset
    minor: Unable to initialize object
  #012: /glade/work/haiyingx/CMake-hdf5-1.12.1/hdf5-1.12.1/src/H5Dint.c line 1287 in H5D__create(): I/O filters can't operate on this dataset
    major: Invalid arguments to routine
    minor: Unable to initialize object
  #013: /glade/work/haiyingx/CMake-hdf5-1.12.1/hdf5-1.12.1/src/H5Z.c line 896 in H5Z_can_apply(): unable to apply filter
    major: Data filters
    minor: Error from filter 'can apply' callback
  #014: /glade/work/haiyingx/CMake-hdf5-1.12.1/hdf5-1.12.1/src/H5Z.c line 857 in H5Z__prepare_prelude_callback_dcpl(): unable to apply filter
    major: Data filters
    minor: Error from filter 'can apply' callback
  #015: /glade/work/haiyingx/CMake-hdf5-1.12.1/hdf5-1.12.1/src/H5Z.c line 758 in H5Z__prelude_callback(): error during user callback
    major: Data filters
    minor: Error from filter 'can apply' callback
  #016: H5Zzfp.c line 148 in H5Z_zfp_can_apply(): ZFP lib not compiled with -DBIT_STREAM_WORD_TYPE=uint8
    major: Data filters
    minor: Unable to initialize object
H5Dcreate failed at line 462, errno=2 (No such file or directory)
HDF5-DIAG: Error detected in HDF5 (1.12.1) thread 0:
  #000: /glade/work/haiyingx/CMake-hdf5-1.12.1/hdf5-1.12.1/src/H5D.c line 285 in H5Dopen2(): unable to open dataset
    major: Dataset
    minor: Can't open object
  #001: /glade/work/haiyingx/CMake-hdf5-1.12.1/hdf5-1.12.1/src/H5VLcallback.c line 1910 in H5VL_dataset_open(): dataset open failed
    major: Virtual Object Layer
    minor: Can't open object
  #002: /glade/work/haiyingx/CMake-hdf5-1.12.1/hdf5-1.12.1/src/H5VLcallback.c line 1877 in H5VL__dataset_open(): dataset open failed
    major: Virtual Object Layer
    minor: Can't open object
  #003: /glade/work/haiyingx/CMake-hdf5-1.12.1/hdf5-1.12.1/src/H5VLnative_dataset.c line 123 in H5VL__native_dataset_open(): unable to open dataset
    major: Dataset
    minor: Can't open object
  #004: /glade/work/haiyingx/CMake-hdf5-1.12.1/hdf5-1.12.1/src/H5Dint.c line 1483 in H5D__open_name(): not found
    major: Dataset
    minor: Object not found
  #005: /glade/work/haiyingx/CMake-hdf5-1.12.1/hdf5-1.12.1/src/H5Gloc.c line 442 in H5G_loc_find(): can't find object
    major: Symbol table
    minor: Object not found
  #006: /glade/work/haiyingx/CMake-hdf5-1.12.1/hdf5-1.12.1/src/H5Gtraverse.c line 837 in H5G_traverse(): internal path traversal failed
    major: Symbol table
    minor: Object not found
  #007: /glade/work/haiyingx/CMake-hdf5-1.12.1/hdf5-1.12.1/src/H5Gtraverse.c line 613 in H5G__traverse_real(): traversal operator failed
    major: Symbol table
    minor: Callback failed
  #008: /glade/work/haiyingx/CMake-hdf5-1.12.1/hdf5-1.12.1/src/H5Gloc.c line 399 in H5G__loc_find_cb(): object 'compressed' doesn't exist
    major: Symbol table
    minor: Object not found
H5Dopen failed at line 156
Library rate test failed for rate=32
Makefile:301: recipe for target 'test-lib-rate' failed
make[1]: *** [test-lib-rate] Error 1
make[1]: Leaving directory '/glade/work/haiyingx/H5Z-ZFP/test'
Makefile:33: recipe for target 'check' failed
make: *** [check] Error 2

**Comment by lindstro** [comment]
> Which default for rounding mode do you recommend or does ZFP use? first or last?

The default is still `-DZFP_ROUNDING_MODE=ZFP_ROUND_NEVER`, which corresponds to what zfp 0.5.x implements.  So you have to explicitly enable "better" rounding.  `ZFP_ROUND_FIRST` is not available for fixed-rate mode (or any expert mode that constrains the rate), while `ZFP_ROUND_LAST` works for all compression modes.

> is there a way for H5Z-ZFP to interrogate which rounding mode ZFP is using/built with?

No, you currently can't, though I can see how that might be desirable in some cases.  Since this is an experimental feature, not much thought has gone into querying/recording the rounding mode or having it recognized in the unit tests.  It's not clear how to handle this better without being able to select the rounding mode at run time and to embed this mode in the zfp header or bitstream, but without breaking backwards compatibility.  For now, this feature is available to users who have very strict demands on error bias.  When `ZFP_ROUND_FIRST` is used, you'll generally get "better" zfp streams that can still be processed.  It's akin to enabling round-to-nearest in IEEE floating point instead of round-toward-zero (truncation).  Those rounding modes will result in different floats, but you can still do computations on them without having to know how they were previously rounded.  I suspect that HDF5 does nothing to record the current setting of the floating-point rounding mode that resulted in a floating-point data set, so maybe H5Z-ZFP shouldn't either. :-)

From the perspective of H5Z-ZFP, when would we want to query the rounding mode and how would we use this information?

**Comment by markcmiller86** [comment]
> No, you currently can't, though I can see how that might be desirable in some cases. Since this is an experimental feature, not much thought has gone into querying/recording the rounding mode or having it recognized in the unit tests.

No worries. I was just thinking about indicating something in the filter name that gets stored to the HDF5 file regarding which rounding was used.

**Comment by markcmiller86** [comment]
> #16: H5Zzfp.c line 148 in H5Z_zfp_can_apply(): ZFP lib not compiled with -DBIT_STREAM_WORD_TYPE=uint8

@halehawk I probably neglected to close the loop here...diagnosing HDF5 error stack messages can be a real pain and there is not anything H5Z-ZFP can do about that but this error message in your error report [above](https://github.com/LLNL/H5Z-ZFP/issues/75#issuecomment-1029346831) is due to not [compiling ZFP](https://h5z-zfp.readthedocs.io/en/latest/installation.html#compiling-zfp) with 8 bit word streams.
