### ISSUE TITLE
Spack install error

### ISSUE THREAD

**Issue by davek44** [LLNL/H5Z-ZFP#9]
Installing via `spack install h5z-zfp`, I encountered the following error. Do you have any advice for getting past this? Thanks!

==> Executing phase: 'edit'
==> Using default implementation: skipping edit phase.
==> Executing phase: 'build'
==> 'make' '-j12' 'PREFIX=/home/drk/code/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/h5z-zfp-0.7.0-tchfkud7llxfepfhq2undgrknbjofykt' 'CC=/home/drk/code/spack/lib/spack/env/gcc/gcc' 'HDF5_HOME=/home/drk/code/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/hdf5-1.10.1-ri5ggz4lmcc7h2ml5uv4xc6cf6ju5kzu' 'ZFP_HOME=/home/drk/code/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/zfp-0.5.1-pihaqxjtwtnes32bjs46l4dvlqzpwg5q' 'FC=/home/drk/code/spack/lib/spack/env/gcc/gfortran' 'all'
cd src; make ZFP_HOME=/home/drk/code/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/zfp-0.5.1-pihaqxjtwtnes32bjs46l4dvlqzpwg5q HDF5_HOME=/home/drk/code/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/hdf5-1.10.1-ri5ggz4lmcc7h2ml5uv4xc6cf6ju5kzu PREFIX=/home/drk/code/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/h5z-zfp-0.7.0-tchfkud7llxfepfhq2undgrknbjofykt all
make[1]: Entering directory `/tmp/drk/spack-stage/spack-stage-_zdn_dju/H5Z-ZFP/src'
/home/drk/code/spack/lib/spack/env/gcc/gcc -c H5Zzfp.c -o H5Zzfp_lib.o -DH5Z_ZFP_AS_LIB -fPIC -I. -I/home/drk/code/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/zfp-0.5.1-pihaqxjtwtnes32bjs46l4dvlqzpwg5q/include -I/home/drk/code/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/hdf5-1.10.1-ri5ggz4lmcc7h2ml5uv4xc6cf6ju5kzu/include
/home/drk/code/spack/lib/spack/env/gcc/gcc -c H5Zzfp_props.c -o H5Zzfp_props.o -fPIC -I. -I/home/drk/code/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/zfp-0.5.1-pihaqxjtwtnes32bjs46l4dvlqzpwg5q/include -I/home/drk/code/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/hdf5-1.10.1-ri5ggz4lmcc7h2ml5uv4xc6cf6ju5kzu/include
/home/drk/code/spack/lib/spack/env/gcc/gfortran -c H5Zzfp_props_f.F90 -o H5Zzfp_props_f.o -fPIC -I. -I/home/drk/code/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/zfp-0.5.1-pihaqxjtwtnes32bjs46l4dvlqzpwg5q/include -I/home/drk/code/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/hdf5-1.10.1-ri5ggz4lmcc7h2ml5uv4xc6cf6ju5kzu/include
/home/drk/code/spack/lib/spack/env/gcc/gcc -c H5Zzfp.c -o H5Zzfp_plugin.o -fPIC -I. -I/home/drk/code/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/zfp-0.5.1-pihaqxjtwtnes32bjs46l4dvlqzpwg5q/include -I/home/drk/code/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/hdf5-1.10.1-ri5ggz4lmcc7h2ml5uv4xc6cf6ju5kzu/include
H5Zzfp_props_f.F90:4.6:

  USE HDF5
      1
Fatal Error: Can't open module file 'hdf5.mod' for reading at (1): No such file or directory
make[1]: *** [H5Zzfp_props_f.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory `/tmp/drk/spack-stage/spack-stage-_zdn_dju/H5Z-ZFP/src'
make: *** [all] Error 2

**Comment by markcmiller86** [comment]
Hmm. Do you need fortran? Can you try `spack install h5z-zfp -fortran`.

Soonest I can look at this in detail is early next week.

**Comment by davek44** [comment]
I get the same result for that command. Thanks for offering to take a look. If there's another path to be able to use zfp from within h5py that you recommend, I'd be happy to try that, too.

**Comment by markcmiller86** [comment]
Hmm. Ok, can you provide more information regarding your development enviornment. Looks like gcc on centos. That said, do you have a fortran compiler there too? The problem you are having seems similar to https://github.com/hyperion-rt/hyperion/issues/23. Or, https://stackoverflow.com/questions/30986415/how-to-compile-a-program-that-need-hdf5-library-using-codeblocks. So, I am just wondering if you built HDF5 library with fortran enabled? By default, I don't think it will build with HDF5 lib with Fortran. So, you could try `spack install h5z-zfp +fortran`. If that causes it to first build HDF5 again, then it may indeed complete successfully for H5Z-ZFP.

An alternative is to just download the H5Z-ZFP release from https://github.com/LLNL/H5Z-ZFP/releases and install it manually too though that would then complicate your spack install point. http://h5z-zfp.readthedocs.io/en/latest/installation.html

Finally, just to be sure, your local fortran compiler there is indeed 2003 or newer, right? H5Z-ZFP requires that due to use of iso_c_binding statements.

**Comment by davek44** [comment]
Hi Mark, I opted to compile from source, and that worked out well. It's certainly possible that my HDF5 wasn't properly configured with fortran. But for now, I'm all set. Thanks!
